#!/usr/bin/env bash
# display best school 10 times with an iteration

count=0
while [ $count -lt 10 ]
do
    if [ $count -eq 9 ]
    then
        echo "Hi"
    fi
    echo "Best School"
    ((count++))
done
