#!/usr/bin/env bash
# display the hours and minutes of a clock

hour=0
while [ $hour -lt 12 ]
do
	echo "Hour: $hour"
	min=0
	while [ $min -lt 59 ]
	do
	        echo "$min"
		(( min ++ ))
	done
	(( hour ++))
done	
