#!/usr/bin/env bash
# creates a file /var/run/myscript.pid
echo $$ > /var/run/myscript.pid

#Displays 'I hate the kill command' when receiving a SIGTERM signal
term(){
        echo'I hate the kill command'
        rm  /var/run/myscript.pid
        exit
}   

# for SIQUIT
quit(){
        rm  /var/run/myscript.pid
        exit
} 

#Displays 'Y U no love me?!' when receiving a SIGINT signal and for SIGTERM
trap 'echo "Y U mo love me?!"' SIGINT
trap 'echo "I hate the kill command"' SIGTERM

# displays 'To infinity and beyond'
while true; do
        echo 'To infinity and beyond'
        sleep 2
done


